### ISSUE TITLE
Fatal git push

### ISSUE THREAD

**Issue by anproulx** [brainhack-school2020/anproulx-fMRI-autism#5]
Hi @dllussier, 
I am trying to push my local Jupyter Notebook to Github, and I am getting this error...

fatal: unable to access 'https://github.com/brainhack-school2020/anproulx-fMRI-autism/': Could not resolve host: github.com

Would you have any idea why?

Thanks a lot!

**Comment by dllussier** [comment]
"Could not resolve host:" is usually a connectivity issue. Were you finally able to push the update?

**Comment by anproulx** [comment]
Yes I resolved the issue thank you. It was indeed a connectivity issue.
